# Generated by Django 5.1.1 on 2024-10-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fololimo', '0007_alter_city_options_alter_subcounty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
