name: Deploy IOT service to production

run-name: deploy-iot

on:
  push:
    branches: ["main"]
    paths:
      - "/iot-svc/**"
      - /'.github/workflows/**'
    tags:
      - "*"
  pull_request:
    branches: ["main"]
    types:
      - closed
  workflow_dispatch:

env:
  IOT_FILE: Dockerfile
  IOT_IMAGE: fololimo-iot:latest
  IOT_CONTEXT: iot-svc

jobs:
  build-artifact:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout the repository
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push server image to registry
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ env.IOT_CONTEXT }}"
          file: ${{env.IOT_FILE}}
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{env.IOT_IMAGE}}

  deploy:
    needs: ["build-artifact"]
    runs-on: ubuntu-latest
    steps:
      - name: ssh to remote server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: "${{ secrets.IOT_REMOTE_HOST }}"
          username: "${{ secrets.IOT_REMOTE_USERNAME }}"
          key: "${{ secrets.IOT_REMOTE_KEY }}"
          port: "${{ secrets.IOT_REMOTE_PORT }}"
          script: |
            REPO_DIR="fololimo-api"

            if [ -d "$REPO_DIR" ]; then
              cd "$REPO_DIR"
              git pull origin main
            else
              git clone "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" "$REPO_DIR"
              cd "$REPO_DIR"
            fi

            chmod u+x ./deploy-iot.sh
            ./deploy-iot.sh
